INSERT INTO public.category ("name") VALUES 
('in voluptate velit es')
,('quis nostr')
,('commodo co')
,('eu fugiat nulla')
,('quis nostrud exercitati')
,('in vo')
,('laboris nisi ut a')
,('elit, sed do ')
,('qui officia deserunt ')
,('sed do eiusmod tempor incidi')
;
INSERT INTO public.category ("name") VALUES 
('Ut enim')
,('consequat. Duis a')
,('exercitation')
,('in vo')
,('nulla pariatur. Excepteur s')
,('consequat. Duis aute ')
,('Ut enim ad minim veniam, qu')
,('anim id est laborum.Lorem')
,('sit amet, consectetur adi')
,('labore et dolore ma')
;
INSERT INTO public.category ("name") VALUES 
('Excepteur sint occaecat cupid')
,('laboris n')
,('quis nostrud e')
,('adipiscing elit, sed do ei')
,('sit ')
,('et dolore magna aliqu')
,('ullamc')
,('ex ea commodo consequat. ')
,('nul')
,('sit ame')
;
INSERT INTO public.category ("name") VALUES 
('in ')
,('velit esse cillum dolore eu f')
,('et dol')
,('deserunt mollit anim id ')
,('velit ess')
,('ut labore et dolore magna aliq')
,('e')
,('ut labore et dolore magn')
,('dolore magna aliqua. Ut e')
,('deserunt mollit anim id est la')
;
INSERT INTO public.category ("name") VALUES 
('con')
,('eiusmod tempor incididunt ut')
,('exercitati')
,('veniam, quis nostru')
,('nu')
,('ad minim ve')
,('laborum.Lorem')
,('ea commodo consequat. Duis a')
,('dolore eu fugiat nulla ')
,('ea commodo consequat. Duis ')
;
INSERT INTO public.category ("name") VALUES 
('cupi')
,('commodo consequ')
,('labore et do')
,('elit, se')
,('occaecat cup')
,('nulla pariat')
,('deserunt')
,('eu fugiat nulla pariatur. E')
,('aliqua. Ut enim ad minim veni')
,('mollit ani')
;
INSERT INTO public.category ("name") VALUES 
('sit am')
,('ali')
,('nisi ut')
,('pariatur. Exc')
,('ut la')
,('deserunt mol')
,('amet, consectetur ')
,('enim ad')
,('in voluptat')
,('id est laborum.Lorem ipsum dol')
;
INSERT INTO public.category ("name") VALUES 
('magna aliqua. Ut enim ')
,('est')
,('cupidatat no')
,('eiusmod tempor inci')
,('in volupt')
,('mollit anim id est lab')
,('velit esse cillu')
,('voluptate velit esse')
,('c')
,('pariatur. Excepteu')
;
INSERT INTO public.category ("name") VALUES 
('ipsum dolor sit amet, consecte')
,('ipsum do')
,('veniam, quis nostrud ')
,('non proident, sunt in culpa q')
,('Duis aute irure d')
,('deserunt moll')
,('ex ea')
,('te')
,('in culpa qui officia deser')
,('incididunt ')
;
INSERT INTO public.category ("name") VALUES 
('tempor incididunt ut l')
,('minim ')
,('cupidatat non ')
,('Duis aute ')
,('velit')
,('ullamco la')
,('anim id est lab')
,('nostrud e')
,('ipsum dolor')
,('ame')
;
INSERT INTO public.category ("name") VALUES 
('velit esse cillu')
,('mollit anim id est laboru')
,('aliqua. Ut enim ad mini')
,('in voluptate velit esse')
,('nulla pariatur')
,('velit ess')
,('Ut enim ad ')
,('commodo con')
,('magna aliqua. Ut enim ad')
,('consequat. Duis aute irur')
;
INSERT INTO public.category ("name") VALUES 
('eu fugiat nulla p')
,('consectetur adip')
,('non proiden')
,('sint occaecat cupi')
,('ullamco laboris n')
,('veli')
,('sunt in culpa qui')
,('id est laborum.Lorem ipsum')
,('a')
,('elit, sed do eiusmod tempor')
;
INSERT INTO public.category ("name") VALUES 
('Ut enim ad minim ve')
,('qui officia deserunt m')
,('in voluptate velit e')
,('aute irure dolor i')
,('Ut enim')
,('Ut enim')
,('in culpa qui officia')
,('laboris nisi ut aliqu')
,('culpa qu')
,('d')
;
INSERT INTO public.category ("name") VALUES 
('in voluptate velit esse')
,('sit amet, consectetur adipis')
,('in volupt')
,('ullamco ')
,('occaecat cu')
,('d')
,('in reprehenderit in voluptat')
,('ut aliquip ex ea com')
,('sit amet, c')
,('pariatur. Excepteur si')
;
INSERT INTO public.category ("name") VALUES 
('eu fugiat nulla pariatur. Exce')
,('Ut enim ad min')
,('exercitation ull')
,('do eiusmod')
,('nisi ut ali')
,('mollit anim id e')
,('in vo')
,('aliqua. Ut ')
,('dese')
,('consequat. Duis ')
;
INSERT INTO public.category ("name") VALUES 
('elit, s')
,('sed do eiusmod tempor incidi')
,('laborum.Lorem ipsum dolor')
,('m.Lorem ipsum')
,('enim ad minim veniam, qui')
,('deser')
,('cillum dolore eu f')
,('magna aliqua. Ut enim ad mi')
,('eiusmod tempor inci')
,('tempor incididunt u')
;
INSERT INTO public.category ("name") VALUES 
('non proident, sunt in cul')
,('adipiscing elit, sed do eiu')
,('sunt in ')
,('adipiscing el')
,('ullamco labor')
,('magna ')
,('su')
,('in volu')
,('consequat. ')
,('pro')
;
INSERT INTO public.category ("name") VALUES 
('cillum dolor')
,('sunt')
,('ea commodo consequat')
,('sed do eiusmod tempor incididu')
,('ipsum dolor sit amet, consecte')
,('id est laborum.Lorem ip')
,('exer')
,('voluptate vel')
,('ex ea commodo cons')
,('commodo consequat. Duis')
;
INSERT INTO public.category ("name") VALUES 
('anim id est lab')
,('mollit anim id est laborum.Lo')
,('sed do eiusmod tempor ')
,('cupidatat non ')
,('exercitation ullamco labo')
,('eu fugiat nulla pariatur. E')
,('adipiscing elit, sed do eiusmo')
,('sit amet, consectetur ')
,('aute irure dolor in reprehende')
,('ut labore et dolore mag')
;
INSERT INTO public.category ("name") VALUES 
('Ut en')
,('est laborum.L')
,('i')
,('deserunt mollit ')
,('dolore')
,('l')
,('eiusmod')
,('labore et dolore magna aliqua')
,('dolor sit amet, consectet')
,('adipiscing elit, sed do eiusmo')
;
INSERT INTO public.category ("name") VALUES 
('ex ea c')
,('nulla pariatur. Excep')
,('est l')
,('laboris nisi ut aliquip ex e')
,('sint occaecat cupidatat')
,('non proident, sunt in culpa ')
,('velit esse cillum dolore eu f')
,('q')
,('dolor')
,('sit amet, conse')
;
INSERT INTO public.category ("name") VALUES 
('fugiat nulla par')
,('ea commodo consequat. ')
,('ad minim veniam, quis nostrud')
,('qui officia deseru')
,('in voluptate v')
,('culpa qui officia deser')
,('commodo cons')
,('sit amet, c')
,('quis nostrud e')
,('sunt in c')
;
INSERT INTO public.category ("name") VALUES 
('nisi ut al')
,('deserunt mollit')
,('ea commodo')
,('consectetur adip')
,('Duis aute irure do')
,('ipsum dolor sit amet')
,('aliqua. Ut enim ad')
,('commodo co')
,('dolore eu fugiat nulla par')
,('labore et dolore m')
;
INSERT INTO public.category ("name") VALUES 
('adipiscing elit, sed do')
,('sed d')
,('eu fugiat nulla pariatur. Exc')
,('Excepte')
,('ut aliquip ex ')
,('incididun')
,('Duis aute i')
,('amet')
,('veniam, quis')
,('Duis aute irure dolor in')
;
INSERT INTO public.category ("name") VALUES 
('in reprehenderit ')
,('quis nostrud exercitati')
,('exer')
,('laboris nisi ut aliqu')
,('officia deserunt mollit anim ')
,('ipsum dol')
,('ullamco laboris nisi ut aliqui')
,('in culpa qui officia deserun')
,('veniam, quis nostrud exer')
,('qui officia deserunt ')
;
INSERT INTO public.category ("name") VALUES 
('irure dolor in re')
,('incididunt ut l')
,('laboris nisi ut ')
,('incididunt ut labore et dol')
,('proident, sunt ')
,('dolore eu fugiat nulla par')
,('eu fugiat nulla pariatu')
,('in voluptate velit esse')
,('cupi')
,('minim veniam, ')
;
INSERT INTO public.category ("name") VALUES 
('cupidatat ')
,('et dolore magna al')
,('incididunt ut labore et')
,('incididunt ut labore e')
,('sint')
,('nisi ut aliquip ex e')
,('laboris nisi ut ')
,('adipiscing e')
,('do e')
,('irure dolor')
;
INSERT INTO public.category ("name") VALUES 
('irure dolor in reprehenderit ')
,('ullamco laboris nisi ut aliqui')
,('cupidatat non proident,')
,('occaecat cupidat')
,('do ')
,('dolore magna aliqua. Ut')
,('veniam, quis nostru')
,('amet, consect')
,('dolore eu fugiat nu')
,('ve')
;
INSERT INTO public.category ("name") VALUES 
('aute iru')
,('non proident, sunt in culpa qu')
,('dolor sit amet, co')
,('et dolore magna aliqua. Ut ')
,('Excepteur sint oc')
,('incididunt ut ')
,('in culpa qui officia deserunt')
,('elit, se')
,('qui officia deserunt moll')
,('nulla pariatur. ')
;
INSERT INTO public.category ("name") VALUES 
('Excepteur sint occaecat cupida')
,('ut labore et dolo')
,('nulla paria')
,('ab')
,('irure')
,('dolor sit amet, co')
,('Duis aute irure dolor in repre')
,('esse cillum d')
,('nisi ut aliquip ex ea comm')
,('sunt in culpa qui officia d')
;
INSERT INTO public.category ("name") VALUES 
('ex ')
,('ip')
,('ullamco l')
,('velit esse cillum dolor')
,('culpa qui officia deserunt mo')
,('anim ')
,('ex ')
,('repreh')
,('sed do eiu')
,('sit')
;
INSERT INTO public.category ("name") VALUES 
('aliqua. Ut enim ad minim v')
,('qui')
,('dolor sit amet, con')
,('incididunt ut la')
,('elit, s')
,('com')
,('laboris nisi u')
,('aliqua. Ut e')
,('consectetur adipisci')
,('consectetur adip')
;
INSERT INTO public.category ("name") VALUES 
('sunt in culpa')
,('s')
,('elit, sed do eiusmo')
,('sed ')
,('culpa qui officia')
,('dolore eu fugiat nulla pariatu')
,('deserunt mollit')
,('in voluptate velit esse ci')
,('deserunt m')
,('pariatur. Excepteur sint occ')
;
INSERT INTO public.category ("name") VALUES 
('ad minim v')
,('cupidatat ')
,('consequat. Duis aute irure do')
,('ulla')
,('quis nostrud e')
,('eu fugiat nulla pariatur. Ex')
,('nostrud exercitation ullamco ')
,('Excepteur sint occ')
,('exer')
,('mollit anim id est ')
;
INSERT INTO public.category ("name") VALUES 
('nisi ut aliquip e')
,('s')
,('Exce')
,('in volupta')
,('laborum.Lorem ipsum dolor sit')
,('magna aliqua. Ut enim ad m')
,('consequat.')
,('cons')
,('laborum.Lorem ipsum dol')
,('um.Lorem ipsum dolor sit')
;
INSERT INTO public.category ("name") VALUES 
('adipisc')
,('ut al')
,('irure dol')
,('ad minim venia')
,('nulla pariatur. Excepteur sint')
,('labo')
,('Duis a')
,('tempo')
,('labor')
,('reprehenderit in voluptate ve')
;
INSERT INTO public.category ("name") VALUES 
('ut aliquip ex ea commodo co')
,('sed do eiu')
,('rum.Lorem ipsum dolor sit am')
,('ex ')
,('nis')
,('Excepteur sint occaecat c')
,('Excepteur sint occaecat')
,('pariatur. Exce')
,('sunt in culpa qui of')
,('amet, consectetur')
;
INSERT INTO public.category ("name") VALUES 
('ipsum dolor sit am')
,('dolore magna aliqua. Ut enim')
,('Excepteur sint occaecat c')
,('et dolore magna aliqua. Ut e')
,('Ut ')
,('dolor')
,('null')
,('elit, sed do e')
,('enim ad minim veni')
,('t')
;
INSERT INTO public.category ("name") VALUES 
('Du')
,('id est lab')
,('in culpa qui officia deserunt ')
,('cupidatat n')
,('ut labore et dolo')
,('ex ea commodo consequat. D')
,('anim id est laborum.Lorem')
,('dolore eu fugiat ')
,('dolore eu fugiat nulla pa')
,('in reprehenderit in voluptate')
;
INSERT INTO public.category ("name") VALUES 
('consectetur')
,('su')
,('aute irure dolor in repre')
,('ex ea commodo consequat.')
,('eu fugiat nulla pariatur. Ex')
,('mollit anim id est laborum.L')
,('ipsum dolor sit amet,')
,('sed do eiusmod tempo')
,('deserunt mollit anim i')
,('dolor sit amet, cons')
;
INSERT INTO public.category ("name") VALUES 
('sunt in culpa qui officia dese')
,('ut labore et dolore magn')
,('est laborum.Lorem ipsum')
,('esse cillum dolore e')
,('a')
,('irure dolor in ')
,('ci')
,('id est laborum.Lorem ips')
,('in culpa')
,('in r')
;
INSERT INTO public.category ("name") VALUES 
('incididunt ut ')
,('occa')
,('cillum dolo')
,('et dolore magna aliqua. Ut ')
,('ad min')
,('culpa qui o')
,('tempor incididunt ut')
,('in')
,('laborum.Lorem')
,('do eiusmod tempor inc')
;
INSERT INTO public.category ("name") VALUES 
('labo')
,('nisi ut aliqui')
,('adip')
,('ad ')
,('dolore magna aliqua. Ut')
,('occaecat c')
,('ex')
,('elit, sed do eiusmod')
,('deserunt mollit an')
,('Excepteur sint occaecat c')
;
INSERT INTO public.category ("name") VALUES 
('officia deseru')
,('ipsum dolor sit amet, con')
,('elit, sed do eiusmod tempo')
,('officia des')
,('non ')
,('amet, consectetur ad')
,('ullamco laboris nisi ut')
,('cupidatat non pro')
,('id est laborum.Lorem')
,('deserunt mollit ')
;
INSERT INTO public.category ("name") VALUES 
('sint occaecat cupidatat n')
,('rum.Lorem ipsum dolor')
,('tempor in')
,('ull')
,('cupidatat non proident, sun')
,('m.Lorem ips')
,('sed do eiusmod tempor incid')
,('adipiscing elit, sed do eius')
,('aliqua.')
,('E')
;
INSERT INTO public.category ("name") VALUES 
('i')
,('si')
,('et')
,('moll')
,('aliqua. ')
,('dolore e')
,('adipiscing elit, sed')
,('laborum.Lorem ipsum dolor sit')
,('elit, sed do eiusmod temp')
,('consectetur adipiscing ')
;
INSERT INTO public.category ("name") VALUES 
('consequat. Duis aute ')
,('elit, sed do ei')
,('laboris nisi ut aliquip e')
,('consec')
,('exercitation ullamco laboris')
,('adipiscing e')
,('nisi ut aliquip ex ea c')
,('quis nostrud exe')
,('ut')
,('irure dolor in reprehenderit i')
;
INSERT INTO public.category ("name") VALUES 
('ut labore et dolore ma')
,('non proident, sunt in cul')
,('in voluptate velit esse ')
,('ulla')
,('la')
,('aliqua')
,('ci')
,('sunt in culpa qui off')
,('anim id est laborum.Lo')
,('Excepteur sint occaecat cu')
;
INSERT INTO public.category ("name") VALUES 
('cupidatat non p')
,('consectetur adipiscin')
,('laboris nisi ut ')
,('laboris nisi ut aliquip')
,('adipisci')
,('Ut enim ad minim venia')
,('veniam, quis nos')
,('dolo')
,('co')
,('aliqua. Ut enim ad')
;
INSERT INTO public.category ("name") VALUES 
('fugiat')
,('officia deserunt molli')
,('Ut enim ad minim ')
,('de')
,('ipsum dolor sit amet, conse')
,('sunt in culpa qui of')
,('m')
,('exercitation ullamco labo')
,('sit amet, co')
,('quis nostrud')
;
INSERT INTO public.category ("name") VALUES 
('dolore ma')
,('reprehenderit in vol')
,('ullamco laboris nisi ')
,('deserunt mollit ')
,('nulla pariatur. Exc')
,('re')
,('ex ea commodo conse')
,('in voluptate velit ')
,('Excepteur s')
,('laboris nisi ut a')
;
INSERT INTO public.category ("name") VALUES 
('tempor incididunt ut labor')
,('adipiscing el')
,('deserunt molli')
,('commodo consequat. Du')
,('ut aliquip ex')
,('magna al')
,('consequat. D')
,('aliquip ex ea commodo con')
,('consectetur adipisc')
,('Ex')
;
INSERT INTO public.category ("name") VALUES 
('do eiusmod te')
,('eiusm')
,('irure dolor in re')
,('in reprehender')
,('eiusmod tempor incidi')
,('culpa qui officia deserunt mol')
,('culpa qui offic')
,('dol')
,('amet, consec')
,('ut labore et dolore ')
;
INSERT INTO public.category ("name") VALUES 
('nisi ut al')
,('ullamco labo')
,('irure dolor in ')
,('in')
,('in voluptate velit')
,('enim ad minim ')
,('Duis aute irure dolor ')
,('Ut enim ad ')
,('sint occaecat cup')
,('con')
;
INSERT INTO public.category ("name") VALUES 
('au')
,('sunt in culpa qui officia ')
,('cillum dolore eu fug')
,('et dolore magna aliqua. ')
,('sit amet, consectetur adipisc')
,('enim ad minim veniam, quis nos')
,('et dolore magna aliqua.')
,('consectetur')
,('quis nostrud ex')
,('adipiscing e')
;
INSERT INTO public.category ("name") VALUES 
('deserunt molli')
,('laboris nisi ut aliquip ')
,('esse cillum dolore eu ')
,('quis nostr')
,('aliquip')
,('est laborum.')
,('deserunt mollit anim id')
,('in repre')
,('ad minim veniam, quis')
,('Excepteur sint occ')
;
INSERT INTO public.category ("name") VALUES 
('sit')
,('Ut enim ad minim venia')
,('su')
,('Ut enim ad minim v')
,('sunt in cul')
,('adipiscing elit, sed do eius')
,('c')
,('Excepteu')
,('et dolore magna aliq')
,('ullamco laboris nisi ut a')
;
INSERT INTO public.category ("name") VALUES 
('non proiden')
,('ir')
,('quis nostrud exer')
,('reprehenderit in voluptate ve')
,('culp')
,('incididunt ut l')
,('Excepteur sin')
,('dolor i')
,('culpa qui officia deserunt mo')
,('n')
;
INSERT INTO public.category ("name") VALUES 
('do eiusmod tempor incididunt')
,('ex ea commod')
,('Exce')
,('nulla pariatur. Excepteur')
,('culpa qui officia d')
,('consequat. Duis')
,('mollit anim id ')
,('et dolore magna ali')
,('pariatur. Excepteu')
,('elit, sed do eiusmod tempo')
;
INSERT INTO public.category ("name") VALUES 
('nisi ')
,('eiusmod te')
,('ess')
,('Duis aute')
,('incididunt ut labo')
,('in v')
,('consequat. Duis aut')
,('in voluptate vel')
,('sint occae')
,('c')
;
INSERT INTO public.category ("name") VALUES 
('ullamco lab')
,('pariatur. Excepteur sint')
,('amet, consectetur adi')
,('ullamco laboris nisi ')
,('fugia')
,('dol')
,('exercitation ullamc')
,('est laborum.Lorem ips')
,('incididunt ut la')
,('mollit anim id est ')
;
INSERT INTO public.category ("name") VALUES 
('nostrud exer')
,('velit')
,('d')
,('Duis aute irure dolor')
,('quis nostrud exerci')
,('ullamco laboris nisi ut al')
,('ullamco laboris ni')
,('veniam, quis nostrud exer')
,('ad minim veniam, quis nost')
,('ut labore et dolore')
;
INSERT INTO public.category ("name") VALUES 
('e')
,('rum.Lorem ipsum dolor')
,('non proident, sunt in culpa qu')
,('cupidatat non proid')
,('esse cillum dolore eu fugiat ')
,('Duis aute ')
,('nulla pariatur. Excepte')
,('culpa qui offi')
,('non proident, sunt in culpa ')
,('exer')
;
INSERT INTO public.category ("name") VALUES 
('eu fugiat nulla')
,('eu ')
,('reprehender')
,('pariatur. Excepteur sint occ')
,('Duis aute irure dolor in ')
,('ut aliquip ex ea co')
,('dolore magna')
,('deserunt m')
,('in voluptate vel')
,('dolor in repr')
;
INSERT INTO public.category ("name") VALUES 
('non proide')
,('elit, sed do eiusmod temp')
,('et dolore magna a')
,('a')
,('in voluptate velit esse ')
,('irure dolor in reprehenderit i')
,('incididunt ut labore et dolore')
,('deseru')
,('magna aliqua.')
,('p')
;
INSERT INTO public.category ("name") VALUES 
('cup')
,('elit, sed do eiusmod tempor ')
,('ad')
,('consectetur adipiscing elit, ')
,('um')
,('cillum dolore eu fugi')
,('Excepteur sint occaecat ')
,('dolor in r')
,('mollit anim id est laborum')
,('Duis aute i')
;
INSERT INTO public.category ("name") VALUES 
('adipiscing elit, sed do ')
,('aliqu')
,('incididunt ut')
,('Excepteur sint oc')
,('in voluptate vel')
,('sunt in')
,('ullamco laboris nisi ut ')
,('sint occaecat cupi')
,('dolore eu fugiat nulla ')
,('minim veniam, quis ')
;
INSERT INTO public.category ("name") VALUES 
('et dolore ')
,('est lab')
,('u')
,('ipsum dolor si')
,('nisi ut aliquip ex ea co')
,('labore et dolore magna al')
,('velit esse cillum dolore')
,('irur')
,('est labor')
,('pariatur. Excepteu')
;
INSERT INTO public.category ("name") VALUES 
('ad minim veniam, quis nost')
,('cupidatat non proide')
,('ut labore et dol')
,('vo')
,('ad minim')
,('dolore magna aliqua. ')
,('elit, sed ')
,('borum.Lorem ipsum dolo')
,('non proident, s')
,('Duis aute i')
;
INSERT INTO public.category ("name") VALUES 
('mollit anim id est la')
,('in voluptate v')
,('consectetur a')
,('sit amet, consectetu')
,('non proident, sunt in culpa ')
,('consequat. Duis ')
,('id est laborum.Lorem ip')
,('u')
,('sed do eiusmod tempor')
,('aliquip ex ea commo')
;
INSERT INTO public.category ("name") VALUES 
('consequat. Duis aut')
,('et dolore magna a')
,('non ')
,('Excepte')
,('qui officia deserun')
,('Lorem ipsum dolor sit am')
,('magna a')
,('Duis aute irure dolor in r')
,('o')
,('adipiscing elit, sed do eiusm')
;
INSERT INTO public.category ("name") VALUES 
('Duis a')
,('ad minim veni')
,('tempor incididunt ut labore et')
,('tempor incididunt ut lab')
,('magna aliqua. Ut e')
,('esse cillum dolore e')
,('ut labore et dolore')
,('Excepteur sint occaecat c')
,('non proident, sunt in culp')
,('dolore eu ')
;
INSERT INTO public.category ("name") VALUES 
('in v')
,('laborum.Lorem ipsum dolor s')
,('dolore eu fugiat null')
,('cupi')
,('aute irur')
,('conse')
,('sint occaecat cupidata')
,('exercitation ullam')
,('Dui')
,('laborum.Lor')
;
INSERT INTO public.category ("name") VALUES 
('pro')
,('officia dese')
,('incididunt ut labore et dolor')
,('qui officia d')
,('in voluptate v')
,('consectetur adipiscing e')
,('ut l')
,('laborum.Lorem ipsum dolor sit')
,('mollit anim id est ')
,('ullamco laboris n')
;
INSERT INTO public.category ("name") VALUES 
('esse cillum ')
,('cillum dolore eu')
,('ullamco laboris nisi u')
,('dolor in')
,('sunt in ')
,('et dolore magna al')
,('qui officia dese')
,('e')
,('magna aliqua. Ut enim ad ')
,('proident, sunt')
;
INSERT INTO public.category ("name") VALUES 
('ad minim ve')
,('sunt in')
,('pariatur. Excepteur ')
,('a')
,('sunt in culpa qui officia des')
,('ut labore ')
,('qui offici')
,('voluptate ve')
,('eu fugiat nulla pari')
,('aute irure dolor in reprehen')
;
INSERT INTO public.category ("name") VALUES 
('in cu')
,('do eiusmod tempor i')
,('ad')
,('ex ea ')
,('fugi')
,('ullamco laboris nisi ut aliq')
,('deseru')
,('nulla pariatur. Excepteu')
,('veniam, quis nost')
,('cill')
;
INSERT INTO public.category ("name") VALUES 
('Exce')
,('cupidatat no')
,('amet, consec')
,('mollit a')
,('anim id est ')
,('nisi ut aliquip ex ea ')
,('dolore eu fugiat nulla pari')
,('non proident, sunt in culpa q')
,('ut aliquip ex ea commodo cons')
,('nulla pari')
;
INSERT INTO public.category ("name") VALUES 
('e')
,('elit, sed do eiusmod tempo')
,('irure dolor in reprehenderi')
,('adipiscing ')
,('e')
,('ullamc')
,('incididunt u')
,('non proident, sunt in c')
,('sit amet, consectetur adipisc')
,('cupida')
;
INSERT INTO public.category ("name") VALUES 
('ad minim veniam, quis')
,('officia deserunt mollit ani')
,('in reprehenderit in volupta')
,('deserunt')
,('ut aliquip ex ea ')
,('ad minim ven')
,('ut labore et dolore ma')
,('mollit anim id est labo')
,('ut labore ')
,('nostrud exer')
;
INSERT INTO public.category ("name") VALUES 
('proiden')
,('et dolore mag')
,('Ut enim a')
,('elit, sed do eiu')
,('elit, sed do eiu')
,('voluptate velit ')
,('adipisci')
,('eiusmod')
,('ad')
,('cupidata')
;
INSERT INTO public.category ("name") VALUES 
('qui officia ')
,('t')
,('laboris nisi ut aliqu')
,('Ut enim ad minim ven')
,('dolore eu fugia')
,('sint occae')
,('commodo cons')
,('Ut enim ad minim ')
,('esse cillum do')
,('ex ea comm')
;
INSERT INTO public.category ("name") VALUES 
('anim ')
,('in voluptate vel')
,('enim ad minim veniam, quis n')
,('velit ')
,('ut labore et d')
,('laborum.L')
,('tempo')
,('sunt in c')
,('nos')
,('magn')
;
INSERT INTO public.category ("name") VALUES 
('consectetur adipisci')
,('exercitation ullamc')
,('ad minim veniam, quis nostr')
,('tempor incididunt ut labore ')
,('est laborum.Lorem ips')
,('Duis aute irur')
,('sunt in culpa qui')
,('laborum.Lorem ips')
,('exerc')
,('anim id ')
;
INSERT INTO public.category ("name") VALUES 
('esse cillu')
,('mollit an')
,('exerci')
,('culpa q')
,('culpa qui officia ')
,('Excepteur sint occaecat cup')
,('sed do')
,('magna ')
,('reprehenderit in voluptate ve')
,('sunt in culpa qu')
;
INSERT INTO public.category ("name") VALUES 
('qui of')
,('cillum ')
,('ullamco laboris nisi ut ali')
,('c')
,('ullamco ')
,('ipsum dolor sit')
,('ullamco laboris nisi ut a')
,('ut labor')
,('velit esse cillum dolore eu')
,('nulla ')
;
INSERT INTO public.category ("name") VALUES 
('ad')
,('amet, consectetur ')
,('quis')
,('ullamco laboris nisi ')
,('dolo')
,('amet, consectetur adipiscing e')
,('au')
,('eu fugiat nulla pariatur. Exc')
,('esse cillum dolore eu fugiat ')
,('elit, sed do eiusmod ')
;
INSERT INTO public.category ("name") VALUES 
('cillum dol')
,('nisi ut aliquip ex ea ')
,('in voluptate ve')
,('ut l')
,('et dolore mag')
,('Excep')
,('deserunt mollit anim ')
,('consectetur adi')
,('consectetur adipiscin')
,('in voluptate velit ')
;
INSERT INTO public.category ("name") VALUES 
('ut labore et d')
,('in culpa qui')
,('ipsum d')
,('adipi')
,('in voluptate')
,('amet')
,('ipsum dolor sit a')
,('est lab')
,('et dolore magna aliqu')
,('cupi')
;
INSERT INTO public.category ("name") VALUES 
('co')
,('in culpa qu')
,('consectetur adi')
,('temp')
,('do eius')
,('velit ess')
,('Excepteur sint occae')
,('in volupt')
,('D')
,('adipiscing elit, sed do e')
;
INSERT INTO public.category ("name") VALUES 
('in vo')
,('deserun')
,('venia')
,('p')
,('magna aliqua. Ut enim ad minim')
,('culpa qui officia deserunt m')
,('occaecat cup')
,('pariatur')
,('ad minim veniam, quis nostr')
,('Excepteur sint occaecat c')
;
INSERT INTO public.category ("name") VALUES 
('Duis aute irure dolo')
,('ut labore e')
,('velit')
,('te')
,('Ut enim ad minim veniam, q')
,('esse cillum dolore eu fugiat ')
,('aborum.Lorem ipsum dolor sit')
,('Duis aute irure dolor i')
,('in voluptate velit')
,('laborum.Lorem')
;
INSERT INTO public.category ("name") VALUES 
('est labo')
,('anim id est laborum.Lorem ip')
,('Ut e')
,('non proident, sunt in culpa')
,('Ut enim ad minim veniam, qu')
,('incididunt ut labore et')
,('esse cillum dolore')
,('proident, sunt i')
,('mollit anim id est labor')
,('mollit anim id est l')
;
INSERT INTO public.category ("name") VALUES 
('in voluptat')
,('sin')
,('anim id est labo')
,('irure dolor in reprehend')
,('sunt in ')
,('dolore eu fugiat nul')
,('nostrud ')
,('anim id est laborum.L')
,('labore et dolo')
,('exercitation ullam')
;
INSERT INTO public.category ("name") VALUES 
('dolor in reprehen')
,('dolore eu fugiat nulla p')
,('cupidatat non proident, sunt i')
,('deserunt mollit anim id e')
,('nostrud exercitation ul')
,('esse cillum dolore eu fug')
,('deserunt molli')
,('.Lorem ipsu')
,('non proident, sunt in culp')
,('Excepteur sint occaec')
;
INSERT INTO public.category ("name") VALUES 
('nulla pariatur')
,('aute irure dolor in reprehend')
,('dolor in reprehende')
,('id est ')
,('ulla')
,('sint occaecat cupidatat')
,('Du')
,('Duis aute irure dolor in ')
,('eu fugiat')
,('esse cillum dolore eu fugiat ')
;
INSERT INTO public.category ("name") VALUES 
('ut labo')
,('deserunt mollit anim')
,('ut labore et dolore mag')
,('nisi ut aliquip ex ea commod')
,('dol')
,('dolor in')
,('um.Lorem ipsum dolor si')
,('elit, sed do eiusmod tempo')
,('tempor ')
,('cup')
;
INSERT INTO public.category ("name") VALUES 
('enim ad')
,('ipsum dolor sit amet')
,('Ut enim ad minim veni')
,('lab')
,('velit esse cil')
,('non proident, sunt in')
,('adipiscing elit, sed do eiu')
,('tempor incididunt ut labore e')
,('Excepteur sin')
,('in voluptate velit esse ci')
;
INSERT INTO public.category ("name") VALUES 
('cupidat')
,('ea commodo consequat. Duis ')
,('Ut enim ad minim veniam, qu')
,('adipiscing elit, sed do ei')
,('in vo')
,('do eiusmod t')
,('ipsum dolor s')
,('velit')
,('do eiusmod tempor ')
,('dolor sit amet, consect')
;
INSERT INTO public.category ("name") VALUES 
('id ')
,('adipiscing elit, sed do eiu')
,('quis nost')
,('in reprehenderit in volup')
,('qui officia dese')
,('reprehenderit in volup')
,('pariatur. Excepteur sint occa')
,('incididunt ut l')
,('c')
,('voluptate ve')
;